### ISSUE TITLE
Erro in sticker command

### ISSUE THREAD

**Issue by AnderRedna** [PikaBotz/Anya_v2-MD#209]
Hi, thanks for the project.

![image](https://github.com/user-attachments/assets/2beb7636-aebd-45c6-961e-983f87e5cae0)

```javascript
0|anya-v2  | Error In Plugin "s": Error: Reached end while reading header
0|anya-v2  |     at WebPReader.readFileHeader (D:\Projetos\1-Maria\MariaBot-Pika\node_modules\node-webpmux\parser.js:57:36)
0|anya-v2  |     at async WebPReader.read (D:\Projetos\1-Maria\MariaBot-Pika\node_modules\node-webpmux\parser.js:163:58)
0|anya-v2  |     at async Image.load (D:\Projetos\1-Maria\MariaBot-Pika\node_modules\node-webpmux\webp.js:207:17)
0|anya-v2  |     at async exports.writeExifImg (D:\Projetos\1-Maria\MariaBot-Pika\lib\lib\converter.js:121:9)
0|anya-v2  |     at async _0x29bd46.<computed> [as sendImageAsSticker] (D:\Projetos\1-Maria\MariaBot-Pika\index.js:35:162747)
0|anya-v2  |     at async Object.function (D:\Projetos\1-Maria\MariaBot-Pika\lib\plugins\convert.js:286:20)
0|anya-v2  |     at async EventEmitter.<anonymous> (D:\Projetos\1-Maria\MariaBot-Pika\index.js:35:142079)
0|anya-v2  | >>> Message 🦋 -s 
0|anya-v2  |  => Requested by Ander xxxxxxxxxxxxx@s.whatsapp.net 
0|anya-v2  |  => Working in Group Chat xxxxxxxxxxxxxxxxx@g.us
0|anya-v2  | Error: forbidden
0|anya-v2  |     at assertNodeErrorFree (D:\Projetos\1-Maria\MariaBot-Pika\node_modules\@queenanya\baileys\lib\WABinary\generic-utils.js:56:15)
0|anya-v2  |     at query (D:\Projetos\1-Maria\MariaBot-Pika\node_modules\@queenanya\baileys\lib\Socket\socket.js:144:48)
0|anya-v2  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|anya-v2  |     at async Object.groupMetadata (D:\Projetos\1-Maria\MariaBot-Pika\node_modules\@queenanya\baileys\lib\Socket\groups.js:22:24)
0|anya-v2  |     at async Promise.all (index 3)
0|anya-v2  |     at async groupEventListener (D:\Projetos\1-Maria\MariaBot-Pika\lib\lib\events.js:47:7007)
0|anya-v2  |     at async EventEmitter.<anonymous> (D:\Projetos\1-Maria\MariaBot-Pika\index.js:35:77844) {
0|anya-v2  |   data: 403,
0|anya-v2  |   isBoom: true,
0|anya-v2  |   isServer: true,
0|anya-v2  |   output: {
0|anya-v2  |     statusCode: 500,
0|anya-v2  |     payload: {
0|anya-v2  |       statusCode: 500,
0|anya-v2  |       error: 'Internal Server Error',
0|anya-v2  |       message: 'An internal server error occurred'
0|anya-v2  |     },
0|anya-v2  |     headers: {}
0|anya-v2  |   }
0|anya-v2  | }
```

**Comment by PikaBotz** [comment]
Yes I saw these errors in my error section but I totally ignored it because it's rare for now and also this error occurs mostly due to media buffer or format issue, major reasons of this issue:

1. Corrupted `webp file`. ***To check this please share me that media here***
2. Incorrect `file input`. ***Although it's hard-coded that u can only use image/video/webp for sticker, and it's not possible to change the access with code edit***
3. Node-webpmux `version issue` ***there's a chance that this could be the issue, lemme update it soon.***

## ⚠️ And please avoid editing codes if you're not a dev, I saw `anyaV2.reply` codeline error warning in your repo but I never defined `anyaV2.reply`

**Comment by Riders004** [comment]
How can I contact you
